version: "3.9"

services:
  mysql:
    image: mysql:8.0
    container_name: vehicle_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: vehicle_dashboard
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build: Backend
    container_name: backend
    restart: always
    depends_on:
      - mysql
    ports:
      - "5000:5000"
    environment:
      PORT: 5000
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: vehicle_dashboard
      JWT_SECRET: supersecretkey

volumes:
  mysql_data:
